spring:
  application:
    name: auth-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  security:
    # Base64 for a 32-byte key: "01234567890123456789012345678901"
    jwt-secret-base64: MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=
    access-token-ttl-seconds: 900
    refresh-token-ttl-seconds: 259200
