apiVersion: v1
kind: Service
metadata:
  name: incident-detection-service
  namespace: ai-observability
spec:
  selector:
    app: incident-detection-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
